package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Arg extends AbsynNode {
    public abstract <R, A> R accept(Arg.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        R visit(latte.Absyn.ArgCode p, A arg);

    }

}
