package latte.Absyn; // Java Package generated by the BNF Converter.

public class Ass  extends Stmt {
  public Target target_;
  public Expr expr_;
  public int line_num, col_num, offset;
  public Ass(Target p1, Expr p2) { target_ = p1; expr_ = p2; }

  public <R,A> R accept(latte.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.Ass) {
      latte.Absyn.Ass x = (latte.Absyn.Ass)o;
      return this.target_.equals(x.target_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.target_.hashCode())+this.expr_.hashCode();
  }


}
