package latte.Absyn; // Java Package generated by the BNF Converter.

public class BlockCode  extends Block {
  public ListStmt liststmt_;
  public int line_num, col_num, offset;
  public BlockCode(ListStmt p1) { liststmt_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof BlockCode) {
      BlockCode x = (BlockCode)o;
      return this.liststmt_.equals(x.liststmt_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststmt_.hashCode();
  }


}
