package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Block extends AbsynNode {
    public abstract <R, A> R accept(Block.Visitor<R, A> v, A arg) ;

    public interface Visitor<R, A> {
        R visit(latte.Absyn.BlockCode p, A arg) ;

    }

}
