package latte.Absyn; // Java Package generated by the BNF Converter.

public class BStmt  extends Stmt {
  public Block block_;
  public int line_num, col_num, offset;
  public BStmt(Block p1) { block_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof BStmt) {
      BStmt x = (BStmt)o;
      return this.block_.equals(x.block_);
    }
    return false;
  }

  public int hashCode() {
    return this.block_.hashCode();
  }


}
