package latte.Absyn; // Java Package generated by the BNF Converter.

public class ClassExt  extends Class {
  public String ident_1, ident_2;
  public ListClassStmt listclassstmt_;
  public int line_num, col_num, offset;
  public ClassExt(String p1, String p2, ListClassStmt p3) { ident_1 = p1; ident_2 = p2; listclassstmt_ = p3; }

  public <R,A> R accept(latte.Absyn.Class.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ClassExt) {
      latte.Absyn.ClassExt x = (latte.Absyn.ClassExt)o;
      return this.ident_1.equals(x.ident_1) && this.ident_2.equals(x.ident_2) && this.listclassstmt_.equals(x.listclassstmt_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_1.hashCode())+this.ident_2.hashCode())+this.listclassstmt_.hashCode();
  }


}
