package latte.Absyn; // Java Package generated by the BNF Converter.

public class ClassCode  extends Class {
  public String ident_;
  public ListClassStmt listclassstmt_;
  public int line_num, col_num, offset;
  public ClassCode(String p1, ListClassStmt p2) { ident_ = p1; listclassstmt_ = p2; }

  public <R,A> R accept(latte.Absyn.Class.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ClassCode) {
      latte.Absyn.ClassCode x = (latte.Absyn.ClassCode)o;
      return this.ident_.equals(x.ident_) && this.listclassstmt_.equals(x.listclassstmt_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.listclassstmt_.hashCode();
  }


}
