package latte.Absyn; // Java Package generated by the BNF Converter.

public class ClassDef  extends TopDef {
  public Class class_;
  public int line_num, col_num, offset;
  public ClassDef(Class p1) { class_ = p1; }

  public <R,A> R accept(latte.Absyn.TopDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.ClassDef) {
      latte.Absyn.ClassDef x = (latte.Absyn.ClassDef)o;
      return this.class_.equals(x.class_);
    }
    return false;
  }

  public int hashCode() {
    return this.class_.hashCode();
  }


}
