package latte.Absyn; // Java Package generated by the BNF Converter.

public class EApp  extends Expr {
  public String ident_;
  public ListExpr listexpr_;
  public int line_num, col_num, offset;
  public EApp(String p1, ListExpr p2) { ident_ = p1; listexpr_ = p2; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof EApp) {
      EApp x = (EApp)o;
      return this.ident_.equals(x.ident_) && this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.listexpr_.hashCode();
  }


}
