package latte.Absyn; // Java Package generated by the BNF Converter.

public class ELitInt  extends Expr {
  public Integer integer_;
  public int line_num, col_num, offset;
  public ELitInt(Integer p1) { integer_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof ELitInt) {
      ELitInt x = (ELitInt)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
