package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Expr implements java.io.Serializable {
  public abstract <R,A> R accept(Expr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(EVar p, A arg);
    public R visit(ELitInt p, A arg);
    public R visit(ELitTrue p, A arg);
    public R visit(ELitFalse p, A arg);
    public R visit(EApp p, A arg);
    public R visit(EString p, A arg);
    public R visit(Neg p, A arg);
    public R visit(Not p, A arg);
    public R visit(EMul p, A arg);
    public R visit(EAdd p, A arg);
    public R visit(ERel p, A arg);
    public R visit(EAnd p, A arg);
    public R visit(EOr p, A arg);

  }

}
