package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Expr extends AbsynNode {
    public abstract <R, A> R accept(Expr.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        R visit(latte.Absyn.EVar p, A arg);

        R visit(latte.Absyn.ELitInt p, A arg);

        R visit(latte.Absyn.ELitTrue p, A arg);

        R visit(latte.Absyn.ELitFalse p, A arg);

        R visit(latte.Absyn.EApp p, A arg);

        R visit(latte.Absyn.EString p, A arg);

        R visit(latte.Absyn.Neg p, A arg);

        R visit(latte.Absyn.Not p, A arg);

        R visit(latte.Absyn.EMul p, A arg);

        R visit(latte.Absyn.EAdd p, A arg);

        R visit(latte.Absyn.ERel p, A arg);

        R visit(latte.Absyn.EAnd p, A arg);

        R visit(latte.Absyn.EOr p, A arg);

    }

}
