package latte.Absyn; // Java Package generated by the BNF Converter.

public class FieldT  extends Target {
  public Expr expr_;
  public String ident_;
  public int line_num, col_num, offset;
  public FieldT(Expr p1, String p2) { expr_ = p1; ident_ = p2; }

  public <R,A> R accept(latte.Absyn.Target.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.FieldT) {
      latte.Absyn.FieldT x = (latte.Absyn.FieldT)o;
      return this.expr_.equals(x.expr_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.ident_.hashCode();
  }


}
