package latte.Absyn; // Java Package generated by the BNF Converter.

public class FnDef  extends TopDef {
  public FunDef fundef_;
  public int line_num, col_num, offset;
  public FnDef(FunDef p1) { fundef_ = p1; }

  public <R,A> R accept(latte.Absyn.TopDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.FnDef) {
      latte.Absyn.FnDef x = (latte.Absyn.FnDef)o;
      return this.fundef_.equals(x.fundef_);
    }
    return false;
  }

  public int hashCode() {
    return this.fundef_.hashCode();
  }


}
