package latte.Absyn; // Java Package generated by the BNF Converter.

public class Incr  extends Stmt {
  public Target target_;
  public int line_num, col_num, offset;
  public Incr(Target p1) { target_ = p1; }

  public <R,A> R accept(latte.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof latte.Absyn.Incr) {
      latte.Absyn.Incr x = (latte.Absyn.Incr)o;
      return this.target_.equals(x.target_);
    }
    return false;
  }

  public int hashCode() {
    return this.target_.hashCode();
  }


}
