package latte.Absyn; // Java Package generated by the BNF Converter.

public class Int  extends Type {
  public int line_num, col_num, offset;
  public Int() { }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Int) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
