package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Item implements java.io.Serializable {
    public String ident_;

    public abstract <R,A> R accept(Item.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(NoInit p, A arg);
    public R visit(Init p, A arg);

  }

}
