package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class MulOp extends AbsynNode {
    public abstract <R, A> R accept(MulOp.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        R visit(latte.Absyn.Times p, A arg);

        R visit(latte.Absyn.Div p, A arg);

        R visit(latte.Absyn.Mod p, A arg);

    }

}
