package latte.Absyn; // Java Package generated by the BNF Converter.

public class NE extends RelOp {
    public NE() {
    }

    public <R, A> R accept(latte.Absyn.RelOp.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        return o instanceof NE;
    }

    public int hashCode() {
        return 37;
    }


}
