package latte.Absyn; // Java Package generated by the BNF Converter.

public class Not  extends Expr {
  public Expr expr_;
  public int line_num, col_num, offset;
  public Not(Expr p1) { expr_ = p1; }

  public <R,A> R accept(Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Not) {
      Not x = (Not)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return this.expr_.hashCode();
  }


}
