package latte.Absyn; // Java Package generated by the BNF Converter.

public class Plus extends AddOp {
    public Plus() {
    }

    public <R, A> R accept(latte.Absyn.AddOp.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        return o instanceof Plus;
    }

    public int hashCode() {
        return 37;
    }


}
