package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Program extends AbsynNode {
    public abstract <R, A> R accept(Program.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        R visit(latte.Absyn.ProgramCode p, A arg);

    }

}
