package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class RelOp implements java.io.Serializable {
  public abstract <R,A> R accept(RelOp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(LTH p, A arg);
    public R visit(LE p, A arg);
    public R visit(GTH p, A arg);
    public R visit(GE p, A arg);
    public R visit(EQU p, A arg);
    public R visit(NE p, A arg);

  }

}
