package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Stmt extends AbsynNode {
    public abstract <R, A> R accept(Stmt.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        R visit(latte.Absyn.Empty p, A arg);

        R visit(latte.Absyn.BStmt p, A arg);

        R visit(latte.Absyn.Decl p, A arg);

        R visit(latte.Absyn.Ass p, A arg);

        R visit(latte.Absyn.Incr p, A arg);

        R visit(latte.Absyn.Decr p, A arg);

        R visit(latte.Absyn.Ret p, A arg);

        R visit(latte.Absyn.VRet p, A arg);

        R visit(latte.Absyn.Cond p, A arg);

        R visit(latte.Absyn.CondElse p, A arg);

        R visit(latte.Absyn.While p, A arg);

        R visit(latte.Absyn.SExp p, A arg);

    }

}
