package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Stmt implements java.io.Serializable {
  public abstract <R,A> R accept(Stmt.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Empty p, A arg);
    public R visit(BStmt p, A arg);
    public R visit(Decl p, A arg);
    public R visit(Ass p, A arg);
    public R visit(Incr p, A arg);
    public R visit(Decr p, A arg);
    public R visit(Ret p, A arg);
    public R visit(VRet p, A arg);
    public R visit(Cond p, A arg);
    public R visit(CondElse p, A arg);
    public R visit(While p, A arg);
    public R visit(SExp p, A arg);

  }

}
