package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Target implements java.io.Serializable {
  public abstract <R,A> R accept(Target.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(latte.Absyn.Variable p, A arg);
    public R visit(latte.Absyn.FieldT p, A arg);

  }

}
