package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class TopDef extends AbsynNode {
    public abstract <R, A> R accept(TopDef.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        R visit(latte.Absyn.FnDef p, A arg);

    }

}
