package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Type implements java.io.Serializable {
  public abstract <R,A> R accept(Type.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Int p, A arg);
    public R visit(Str p, A arg);
    public R visit(Bool p, A arg);
    public R visit(Void p, A arg);
    public R visit(Fun p, A arg);

  }

}
