package latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Type extends AbsynNode {
    public abstract <R, A> R accept(Type.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        R visit(latte.Absyn.Int p, A arg);

        R visit(latte.Absyn.Str p, A arg);

        R visit(latte.Absyn.Bool p, A arg);

        R visit(latte.Absyn.Void p, A arg);

        R visit(latte.Absyn.Fun p, A arg);

    }

}
