package latte.Absyn; // Java Package generated by the BNF Converter.

public class Void extends Type {
    public Void() {
    }

    public <R, A> R accept(latte.Absyn.Type.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        return o instanceof Void;
    }

    public int hashCode() {
        return 37;
    }


}
