// This LatteClasses.JLex file was machine-generated by the BNF converter
package latte;
import java_cup.runtime.*;


public class Yylex implements java_cup.runtime.Scanner {
	private int YY_BUFFER_SIZE = 512;
	private int YY_F = -1;
	private int YY_NO_STATE = -1;
	private int YY_NOT_ACCEPT = 0;
	private int YY_START = 1;
	private int YY_END = 2;
	private int YY_NO_ANCHOR = 4;
	private int YY_BOL = 65536;
	private int YY_EOF = 65537;

  String pstring = new String();
  int unknown = -1;
  ComplexSymbolFactory.Location left = new ComplexSymbolFactory.Location(unknown, unknown);
  ComplexSymbolFactory cf = new ComplexSymbolFactory();
  public SymbolFactory getSymbolFactory() { return cf; }
  int yycolumn = unknown - 1;
  public int line_num() { return (yyline+1); }
  public ComplexSymbolFactory.Location left_loc() {
    return new ComplexSymbolFactory.Location(yyline+1, yycolumn+1, yychar);
  }
  public ComplexSymbolFactory.Location right_loc() {
    ComplexSymbolFactory.Location left = left_loc();
  return new ComplexSymbolFactory.Location(left.getLine(), left.getColumn()+yylength(), left.getOffset()+yylength());
  }
  public String buff() {return new String(yy_buffer,yy_buffer_index,10).trim();}
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private int yychar;
	private int yyline;
	private boolean yy_at_bol;
	private int yy_lexical_state;

	public Yylex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	public Yylex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Yylex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yychar = 0;
		yyline = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private int STRING = 5;
	private int ESCAPED = 6;
	private int YYINITIAL = 0;
	private int COMMENT = 1;
	private int CHAREND = 4;
	private int CHARESC = 3;
	private int CHAR = 2;
	private int yy_state_dtrans[] = {
		0,
		65,
		71,
		71,
		71,
		74,
		76
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		int i;
		for (i = yy_buffer_start; i < yy_buffer_index; ++i) {
			if ('\n' == yy_buffer[i] && !yy_last_was_cr) {
				++yyline;
			}
			if ('\r' == yy_buffer[i]) {
				++yyline;
				yy_last_was_cr=true;
			} else yy_last_was_cr=false;
		}
		yychar = yychar
			+ yy_buffer_index - yy_buffer_start;
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private int YY_E_INTERNAL = 0;
	private int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NO_ANCHOR,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NO_ANCHOR,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NO_ANCHOR,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NO_ANCHOR,
		/* 37 */ YY_NO_ANCHOR,
		/* 38 */ YY_NO_ANCHOR,
		/* 39 */ YY_NO_ANCHOR,
		/* 40 */ YY_NO_ANCHOR,
		/* 41 */ YY_NO_ANCHOR,
		/* 42 */ YY_NO_ANCHOR,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NO_ANCHOR,
		/* 45 */ YY_NO_ANCHOR,
		/* 46 */ YY_NO_ANCHOR,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NO_ANCHOR,
		/* 49 */ YY_NO_ANCHOR,
		/* 50 */ YY_NO_ANCHOR,
		/* 51 */ YY_NO_ANCHOR,
		/* 52 */ YY_NO_ANCHOR,
		/* 53 */ YY_NO_ANCHOR,
		/* 54 */ YY_NO_ANCHOR,
		/* 55 */ YY_NO_ANCHOR,
		/* 56 */ YY_NO_ANCHOR,
		/* 57 */ YY_NO_ANCHOR,
		/* 58 */ YY_NO_ANCHOR,
		/* 59 */ YY_NO_ANCHOR,
		/* 60 */ YY_NO_ANCHOR,
		/* 61 */ YY_NO_ANCHOR,
		/* 62 */ YY_NO_ANCHOR,
		/* 63 */ YY_NO_ANCHOR,
		/* 64 */ YY_NO_ANCHOR,
		/* 65 */ YY_NOT_ACCEPT,
		/* 66 */ YY_NO_ANCHOR,
		/* 67 */ YY_NO_ANCHOR,
		/* 68 */ YY_NO_ANCHOR,
		/* 69 */ YY_NO_ANCHOR,
		/* 70 */ YY_NO_ANCHOR,
		/* 71 */ YY_NOT_ACCEPT,
		/* 72 */ YY_NO_ANCHOR,
		/* 73 */ YY_NO_ANCHOR,
		/* 74 */ YY_NOT_ACCEPT,
		/* 75 */ YY_NO_ANCHOR,
		/* 76 */ YY_NOT_ACCEPT,
		/* 77 */ YY_NO_ANCHOR,
		/* 78 */ YY_NO_ANCHOR,
		/* 79 */ YY_NO_ANCHOR,
		/* 80 */ YY_NO_ANCHOR,
		/* 81 */ YY_NO_ANCHOR,
		/* 82 */ YY_NO_ANCHOR,
		/* 83 */ YY_NO_ANCHOR,
		/* 84 */ YY_NO_ANCHOR,
		/* 85 */ YY_NO_ANCHOR,
		/* 86 */ YY_NO_ANCHOR,
		/* 87 */ YY_NO_ANCHOR,
		/* 88 */ YY_NO_ANCHOR,
		/* 89 */ YY_NO_ANCHOR,
		/* 90 */ YY_NO_ANCHOR,
		/* 91 */ YY_NO_ANCHOR,
		/* 92 */ YY_NO_ANCHOR,
		/* 93 */ YY_NO_ANCHOR,
		/* 94 */ YY_NO_ANCHOR,
		/* 95 */ YY_NO_ANCHOR,
		/* 96 */ YY_NO_ANCHOR,
		/* 97 */ YY_NO_ANCHOR,
		/* 98 */ YY_NO_ANCHOR,
		/* 99 */ YY_NO_ANCHOR,
		/* 100 */ YY_NO_ANCHOR,
		/* 101 */ YY_NO_ANCHOR,
		/* 102 */ YY_NO_ANCHOR,
		/* 103 */ YY_NO_ANCHOR,
		/* 104 */ YY_NO_ANCHOR,
		/* 105 */ YY_NO_ANCHOR,
		/* 106 */ YY_NO_ANCHOR,
		/* 107 */ YY_NO_ANCHOR,
		/* 108 */ YY_NO_ANCHOR,
		/* 109 */ YY_NO_ANCHOR,
		/* 110 */ YY_NO_ANCHOR,
		/* 111 */ YY_NO_ANCHOR,
		/* 112 */ YY_NO_ANCHOR,
		/* 113 */ YY_NO_ANCHOR,
		/* 114 */ YY_NO_ANCHOR,
		/* 115 */ YY_NO_ANCHOR,
		/* 116 */ YY_NO_ANCHOR,
		/* 117 */ YY_NO_ANCHOR,
		/* 118 */ YY_NO_ANCHOR,
		/* 119 */ YY_NO_ANCHOR,
		/* 120 */ YY_NO_ANCHOR,
		/* 121 */ YY_NO_ANCHOR,
		/* 122 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,65538,
"40:9,48,41,40,48,39,40:18,48,13,42,38,40,18,14,47,1,2,16,9,3,10,7,17,44:10," +
"40,6,11,8,12,40:2,45:26,40,43,40:2,47,40,23,19,25,29,22,30,35,37,31,46:2,21" +
",46,24,20,46:2,34,26,28,33,36,32,27,46:2,4,15,5,40:66,45:23,40,45:7,46:24,4" +
"0,46:8,40:65280,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,123,
"0,1:8,2,3,4,5,6,7,8,1,9,1,10,11,1:2,12,1:11,13,14:14,1:4,15,1:7,16,1:2,17,1" +
"8,19,20,1:2,21,1,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,4" +
"1,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,6" +
"6,67,68,14,69,14")[0];

	private int yy_nxt[][] = unpackFromString(70,49,
"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,66,16,17,18,19,122:2,100,122,88,110,117" +
",122,101,122,111,67,112,122,118,122,102,122,20,21,72,21,22,72,23,122:2,72,2" +
"1,-1:57,24,-1:49,25,-1:49,26,-1:46,27,-1:2,28,-1:45,29,-1:3,30,-1:44,31,-1:" +
"54,32,-1:50,34,35,-1:50,122,119,122:17,-1:6,120:2,122,120,-1:2,20:40,-1,20:" +
"7,-1:44,23,-1:5,35:40,-1,35:7,-1:19,122:19,-1:6,120:2,122,120,-1:42,69,-1:4" +
"8,70,-1:7,1,50:15,68,50:22,-1,50,51,50:7,-1:15,33,-1:52,122:5,75,122:5,36,1" +
"22:7,-1:6,120:2,122,120,-1:18,52,-1:31,1,72:38,-1,72,-1,72:7,-1:19,122:13,3" +
"7,122:5,-1:6,120:2,122,120,-1,1,53:38,54,53,69,55,56,53:5,-1:19,122:9,38,12" +
"2:9,-1:6,120:2,122,120,-1,1,57:23,58,57:3,59,57,60,57:3,61,57:4,62,57,70,63" +
",64,57:5,-1:19,122:3,39,122:15,-1:6,120:2,122,120,-1:20,122:2,40,122:16,-1:" +
"6,120:2,122,120,-1:20,122:3,41,122:15,-1:6,120:2,122,120,-1:20,122:10,42,12" +
"2:8,-1:6,120:2,122,120,-1:20,122:7,43,122:11,-1:6,120:2,122,120,-1:20,122:3" +
",44,122:15,-1:6,120:2,122,120,-1:20,122:3,45,122:15,-1:6,120:2,122,120,-1:2" +
"0,122:16,46,122:2,-1:6,120:2,122,120,-1:20,122:5,47,122:13,-1:6,120:2,122,1" +
"20,-1:20,122:5,48,122:13,-1:6,120:2,122,120,-1:20,122:7,49,122:11,-1:6,120:" +
"2,122,120,-1:20,122:3,73,122:10,90,122:4,-1:6,120:2,122,120,-1:20,122:7,77," +
"122:11,-1:6,120:2,122,120,-1:20,122:2,78,122:16,-1:6,120:2,122,120,-1:20,12" +
"2:14,79,122:4,-1:6,120:2,122,120,-1:20,122:12,80,122:6,-1:6,120:2,122,120,-" +
"1:20,122:7,81,122:11,-1:6,120:2,122,120,-1:20,122:7,82,122:11,-1:6,120:2,12" +
"2,120,-1:20,122:2,83,122:16,-1:6,120:2,122,120,-1:20,122:5,84,122:13,-1:6,1" +
"20:2,122,120,-1:20,122:15,85,122:3,-1:6,120:2,122,120,-1:20,122:4,86,122:14" +
",-1:6,120:2,122,120,-1:20,122:10,87,122:8,-1:6,120:2,122,120,-1:20,122:2,89" +
",122:5,121,122:10,-1:6,120:2,122,120,-1:20,122:15,91,122:3,-1:6,120:2,122,1" +
"20,-1:20,122,92,122:17,-1:6,120:2,122,120,-1:20,122:4,93,122:14,-1:6,120:2," +
"122,120,-1:20,122:2,94,122:16,-1:6,120:2,122,120,-1:20,122:12,95,122:6,-1:6" +
",120:2,122,120,-1:20,122:12,96,122:6,-1:6,120:2,122,120,-1:20,122:14,97,122" +
":4,-1:6,120:2,122,120,-1:20,122:3,98,122:15,-1:6,120:2,122,120,-1:20,122:5," +
"99,122:13,-1:6,120:2,122,120,-1:20,122:2,103,122:16,-1:6,120:2,122,120,-1:2" +
"0,122:4,104,122:14,-1:6,120:2,122,120,-1:20,122:18,105,-1:6,120:2,122,120,-" +
"1:20,122:15,106,122:3,-1:6,120:2,122,120,-1:20,122:9,107,122:9,-1:6,120:2,1" +
"22,120,-1:20,122:2,108,122:16,-1:6,120:2,122,120,-1:20,122:3,109,122:15,-1:" +
"6,120:2,122,120,-1:20,122:9,113,122:9,-1:6,120:2,122,120,-1:20,122:3,114,12" +
"2:15,-1:6,120:2,122,120,-1:20,122,115,122:17,-1:6,120:2,122,120,-1:20,122:9" +
",116,122:9,-1:6,120:2,122,120,-1");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {

  return cf.newSymbol("EOF", latte.sym.EOF, left_loc(), left_loc());
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return cf.newSymbol("", latte.sym._SYMB_0, left_loc(), right_loc()); }
					case -3:
						break;
					case 3:
						{ return cf.newSymbol("", latte.sym._SYMB_1, left_loc(), right_loc()); }
					case -4:
						break;
					case 4:
						{ return cf.newSymbol("", latte.sym._SYMB_2, left_loc(), right_loc()); }
					case -5:
						break;
					case 5:
						{ return cf.newSymbol("", latte.sym._SYMB_3, left_loc(), right_loc()); }
					case -6:
						break;
					case 6:
						{ return cf.newSymbol("", latte.sym._SYMB_4, left_loc(), right_loc()); }
					case -7:
						break;
					case 7:
						{ return cf.newSymbol("", latte.sym._SYMB_5, left_loc(), right_loc()); }
					case -8:
						break;
					case 8:
						{ return cf.newSymbol("", latte.sym._SYMB_6, left_loc(), right_loc()); }
					case -9:
						break;
					case 9:
						{ return cf.newSymbol("", latte.sym._SYMB_7, left_loc(), right_loc()); }
					case -10:
						break;
					case 10:
						{ return cf.newSymbol("", latte.sym._SYMB_16, left_loc(), right_loc()); }
					case -11:
						break;
					case 11:
						{ return cf.newSymbol("", latte.sym._SYMB_12, left_loc(), right_loc()); }
					case -12:
						break;
					case 12:
						{ return cf.newSymbol("", latte.sym._SYMB_20, left_loc(), right_loc()); }
					case -13:
						break;
					case 13:
						{ return cf.newSymbol("", latte.sym._SYMB_22, left_loc(), right_loc()); }
					case -14:
						break;
					case 14:
						{ return cf.newSymbol("", latte.sym._SYMB_13, left_loc(), right_loc()); }
					case -15:
						break;
					case 15:
						{ throw new Error("Illegal Character <"+yytext()+"> at "+(yyline+1)); }
					case -16:
						break;
					case 16:
						{ return cf.newSymbol("", latte.sym._SYMB_17, left_loc(), right_loc()); }
					case -17:
						break;
					case 17:
						{ return cf.newSymbol("", latte.sym._SYMB_18, left_loc(), right_loc()); }
					case -18:
						break;
					case 18:
						{ return cf.newSymbol("", latte.sym._SYMB_19, left_loc(), right_loc()); }
					case -19:
						break;
					case 19:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -20:
						break;
					case 20:
						{ /* skip */ }
					case -21:
						break;
					case 21:
						{ /* ignore white space. */ }
					case -22:
						break;
					case 22:
						{ left = left_loc(); yybegin(STRING); }
					case -23:
						break;
					case 23:
						{ return cf.newSymbol("", latte.sym._INTEGER_, left_loc(), right_loc(), new Integer(yytext())); }
					case -24:
						break;
					case 24:
						{ return cf.newSymbol("", latte.sym._SYMB_24, left_loc(), right_loc()); }
					case -25:
						break;
					case 25:
						{ return cf.newSymbol("", latte.sym._SYMB_8, left_loc(), right_loc()); }
					case -26:
						break;
					case 26:
						{ return cf.newSymbol("", latte.sym._SYMB_9, left_loc(), right_loc()); }
					case -27:
						break;
					case 27:
						{ return cf.newSymbol("", latte.sym._SYMB_21, left_loc(), right_loc()); }
					case -28:
						break;
					case 28:
						{ return cf.newSymbol("", latte.sym._SYMB_10, left_loc(), right_loc()); }
					case -29:
						break;
					case 29:
						{ return cf.newSymbol("", latte.sym._SYMB_23, left_loc(), right_loc()); }
					case -30:
						break;
					case 30:
						{ return cf.newSymbol("", latte.sym._SYMB_11, left_loc(), right_loc()); }
					case -31:
						break;
					case 31:
						{ return cf.newSymbol("", latte.sym._SYMB_25, left_loc(), right_loc()); }
					case -32:
						break;
					case 32:
						{ return cf.newSymbol("", latte.sym._SYMB_14, left_loc(), right_loc()); }
					case -33:
						break;
					case 33:
						{ return cf.newSymbol("", latte.sym._SYMB_15, left_loc(), right_loc()); }
					case -34:
						break;
					case 34:
						{ yybegin(COMMENT); }
					case -35:
						break;
					case 35:
						{ /* skip */ }
					case -36:
						break;
					case 36:
						{ return cf.newSymbol("", latte.sym._SYMB_31, left_loc(), right_loc()); }
					case -37:
						break;
					case 37:
						{ return cf.newSymbol("", latte.sym._SYMB_33, left_loc(), right_loc()); }
					case -38:
						break;
					case 38:
						{ return cf.newSymbol("", latte.sym._SYMB_32, left_loc(), right_loc()); }
					case -39:
						break;
					case 39:
						{ return cf.newSymbol("", latte.sym._SYMB_28, left_loc(), right_loc()); }
					case -40:
						break;
					case 40:
						{ return cf.newSymbol("", latte.sym._SYMB_34, left_loc(), right_loc()); }
					case -41:
						break;
					case 41:
						{ return cf.newSymbol("", latte.sym._SYMB_37, left_loc(), right_loc()); }
					case -42:
						break;
					case 42:
						{ return cf.newSymbol("", latte.sym._SYMB_38, left_loc(), right_loc()); }
					case -43:
						break;
					case 43:
						{ return cf.newSymbol("", latte.sym._SYMB_27, left_loc(), right_loc()); }
					case -44:
						break;
					case 44:
						{ return cf.newSymbol("", latte.sym._SYMB_30, left_loc(), right_loc()); }
					case -45:
						break;
					case 45:
						{ return cf.newSymbol("", latte.sym._SYMB_39, left_loc(), right_loc()); }
					case -46:
						break;
					case 46:
						{ return cf.newSymbol("", latte.sym._SYMB_36, left_loc(), right_loc()); }
					case -47:
						break;
					case 47:
						{ return cf.newSymbol("", latte.sym._SYMB_35, left_loc(), right_loc()); }
					case -48:
						break;
					case 48:
						{ return cf.newSymbol("", latte.sym._SYMB_26, left_loc(), right_loc()); }
					case -49:
						break;
					case 49:
						{ return cf.newSymbol("", latte.sym._SYMB_29, left_loc(), right_loc()); }
					case -50:
						break;
					case 50:
						{ /* skip */ }
					case -51:
						break;
					case 51:
						{ /* skip */ }
					case -52:
						break;
					case 52:
						{ yybegin(YYINITIAL); }
					case -53:
						break;
					case 53:
						{ pstring += yytext(); }
					case -54:
						break;
					case 54:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -55:
						break;
					case 55:
						{ String foo = pstring; pstring = new String(); yybegin(YYINITIAL); return cf.newSymbol("", latte.sym._STRING_, left, right_loc(), foo.intern()); }
					case -56:
						break;
					case 56:
						{ yybegin(ESCAPED); }
					case -57:
						break;
					case 57:
						{ pstring += yytext(); yybegin(STRING); }
					case -58:
						break;
					case 58:
						{ pstring +=  "\n"; yybegin(STRING); }
					case -59:
						break;
					case 59:
						{ pstring += "\t"; yybegin(STRING); }
					case -60:
						break;
					case 60:
						{ pstring += "\f"; yybegin(STRING); }
					case -61:
						break;
					case 61:
						{ pstring += "\r"; yybegin(STRING); }
					case -62:
						break;
					case 62:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -63:
						break;
					case 63:
						{ pstring += "\""; yybegin(STRING); }
					case -64:
						break;
					case 64:
						{ pstring += "\\"; yybegin(STRING); }
					case -65:
						break;
					case 66:
						{ throw new Error("Illegal Character <"+yytext()+"> at "+(yyline+1)); }
					case -66:
						break;
					case 67:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -67:
						break;
					case 68:
						{ /* skip */ }
					case -68:
						break;
					case 69:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -69:
						break;
					case 70:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -70:
						break;
					case 72:
						{ throw new Error("Illegal Character <"+yytext()+"> at "+(yyline+1)); }
					case -71:
						break;
					case 73:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -72:
						break;
					case 75:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -73:
						break;
					case 77:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -74:
						break;
					case 78:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -75:
						break;
					case 79:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -76:
						break;
					case 80:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -77:
						break;
					case 81:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -78:
						break;
					case 82:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -79:
						break;
					case 83:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -80:
						break;
					case 84:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -81:
						break;
					case 85:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -82:
						break;
					case 86:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -83:
						break;
					case 87:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -84:
						break;
					case 88:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -85:
						break;
					case 89:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -86:
						break;
					case 90:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -87:
						break;
					case 91:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -88:
						break;
					case 92:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -89:
						break;
					case 93:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -90:
						break;
					case 94:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -91:
						break;
					case 95:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -92:
						break;
					case 96:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -93:
						break;
					case 97:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -94:
						break;
					case 98:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -95:
						break;
					case 99:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -96:
						break;
					case 100:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -97:
						break;
					case 101:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -98:
						break;
					case 102:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -99:
						break;
					case 103:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -100:
						break;
					case 104:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -101:
						break;
					case 105:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -102:
						break;
					case 106:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -103:
						break;
					case 107:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -104:
						break;
					case 108:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -105:
						break;
					case 109:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -106:
						break;
					case 110:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -107:
						break;
					case 111:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -108:
						break;
					case 112:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -109:
						break;
					case 113:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -110:
						break;
					case 114:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -111:
						break;
					case 115:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -112:
						break;
					case 116:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -113:
						break;
					case 117:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -114:
						break;
					case 118:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -115:
						break;
					case 119:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -116:
						break;
					case 120:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -117:
						break;
					case 121:
						{ return cf.newSymbol("", latte.sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -118:
						break;
					case 122:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -119:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
